const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)],K='tmh3_';
const DEFAULT_MEMBERS=[{id:'m1',name:'Subramaniam',password:'mind1',bio:'Add your story, interests, skills and what you are learning.',photo:''},{id:'m2',name:'Pradap',password:'mind2',bio:'Write your personal blog for your two friends.',photo:''},{id:'m3',name:'Kalaivani',password:'mind3',bio:'A little introduction about me goes here.',photo:''}];
const empty={posts:[],memories:[],media:[],files:[],goals:[],events:[],notes:[]};
const load=(k,v)=>{try{return JSON.parse(localStorage.getItem(K+k))??structuredClone(v)}catch{return structuredClone(v)}};const save=(k,v)=>localStorage.setItem(K+k,JSON.stringify(v));
let members=load('members',DEFAULT_MEMBERS),d=Object.fromEntries(Object.keys(empty).map(k=>[k,load(k,empty[k])]));let cur=localStorage.getItem(K+'cur')||'';
const esc=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));const me=()=>members.find(x=>x.id===cur)||members[0];const mm=id=>members.find(x=>x.id===id)||members[0];const fmt=x=>x?new Date(x+'T00:00:00').toLocaleDateString(undefined,{day:'numeric',month:'short',year:'numeric'}):'';
const readFile=f=>new Promise(r=>{const x=new FileReader;x.onload=()=>r(x.result);x.readAsDataURL(f)});
function note(text){d.notes.unshift({id:Date.now(),text,unread:1});d.notes=d.notes.slice(0,40);save('notes',d.notes)}
function injectStyle(){let s=document.createElement('style');s.textContent=`#headerLogout{display:none!important}.heroLogo{width:100%}.campfireScene{width:min(470px,88vw);aspect-ratio:1.05;border-radius:34px;position:relative;overflow:hidden;background:linear-gradient(#17253d 0 54%,#29221d 55%);box-shadow:0 22px 60px #0003;border:7px solid #fff8}.campfireScene:before{content:'✦  ·   ✦       ·  ✦\\A    ·       ✦     ·\\A  ✦      ·     ✦';white-space:pre;position:absolute;inset:18px;color:#fff9;font-size:18px;line-height:2.4}.moon{position:absolute;right:14%;top:11%;width:68px;height:68px;border-radius:50%;background:#fff4cf;box-shadow:0 0 35px #fff1a966}.hill{position:absolute;left:-10%;right:-10%;bottom:24%;height:42%;background:#141814;border-radius:50% 50% 0 0}.log{position:absolute;bottom:21%;left:34%;width:32%;height:22px;border-radius:15px;background:linear-gradient(90deg,#5d3622,#a35f35,#4a291c);transform:rotate(10deg)}.log.two{transform:rotate(-10deg)}.fire{position:absolute;left:43%;bottom:21%;width:18%;height:27%;background:radial-gradient(circle at 50% 75%,#fff3a8 0 12%,#ffcf3d 13% 35%,#ff6a2e 36% 68%,transparent 69%);clip-path:polygon(50% 0,68% 35%,100% 55%,75% 100%,25% 100%,0 55%,32% 35%);filter:drop-shadow(0 0 16px #ff812c)}.campCaption{position:absolute;left:24px;bottom:20px;color:#fff;font-weight:800;text-shadow:0 2px 8px #000}.themeToggle{width:88px!important;height:42px!important;position:relative!important}.themeToggle span:last-child{font-size:22px!important}.profileMini{width:42px!important;height:42px!important}.profileMini img{width:100%;height:100%;object-fit:cover;border-radius:50%}.flagIndia{width:23px;height:17px;border:1px solid #aaa;border-radius:2px;display:inline-block;position:relative;background:linear-gradient(#ff9933 0 33.3%,#fff 33.3% 66.6%,#138808 66.6%);box-shadow:0 2px 7px #0002}.flagIndia:after{content:'';position:absolute;width:4px;height:4px;border:1px solid #2454a6;border-radius:50%;left:50%;top:50%;transform:translate(-50%,-50%)}.social a{background:transparent!important;border-radius:0!important}.social a:hover{background:transparent!important}.max10{font-size:13px!important;font-weight:700;color:var(--muted);margin-left:5px}.rowDelete{position:absolute;right:0;top:12px;width:30px;height:30px;border:1px solid var(--line);border-radius:8px;background:transparent;color:var(--muted)}.rowDelete:hover{color:#c34b42;border-color:#c34b42}.goal,.event{position:relative;padding-right:44px}.notification.readNote{background:#e7e7e7!important;color:#8b8b8b!important;border-color:#d8d8d8!important}.clearBtn{margin-left:7px}.shareOptions{grid-template-columns:1fr 1fr}.media audio{width:90%}@media(max-width:600px){.campfireScene{width:290px}.themeToggle{width:78px!important}}`;document.head.appendChild(s)}
function hero(){let h=$('.heroLogo');if(!h)return;h.innerHTML=`<div class="campfireScene"><div class="moon"></div><div class="hill"></div><div class="log"></div><div class="log two"></div><div class="fire"></div><div class="campCaption">A quiet place for three friends to meet, remember and grow.</div></div>`;let heroP=document.querySelector('.hero>div:first-child>p:not(.eyebrow):not(.campCaption)');if(heroP)heroP.textContent='A private digital campfire for real memories, honest conversations, shared moments and learning together.'}
function setupHeader(){let h=$('#hamb');if(h)h.onclick=()=>$('#menu').classList.add('open');if($('#x'))$('#x').onclick=()=>$('#menu').classList.remove('open');$$('#menu a').forEach(a=>a.onclick=()=>$('#menu').classList.remove('open'));if($('#logout'))$('#logout').onclick=logout;if($('#headerLogout'))$('#headerLogout').style.display='none';let india=document.createElement('span');india.className='flagIndia';india.title='India';india.setAttribute('aria-label','India');$('.headerTools')?.prepend(india);let t=$('#themeToggle');if(t){t.onclick=()=>{document.body.classList.toggle('dark');t.classList.toggle('on');localStorage.setItem(K+'dark',document.body.classList.contains('dark'))};if(localStorage.getItem(K+'dark')==='true'){document.body.classList.add('dark');t.classList.add('on')}}}
function logout(){localStorage.removeItem(K+'cur');location.reload()}
function profileIcon(){let b=$('#me'),m=me();if(!b)return;if(m.photo)b.innerHTML=`<img src="${m.photo}" alt="${esc(m.name)}">`;else b.textContent=m.name[0]}
function boot(){injectStyle();setupHeader();hero();$('#who').innerHTML=members.map(x=>`<option value="${x.id}">${esc(x.name)}</option>`).join('');if(cur){$('#login').classList.add('hide');$('#app').classList.remove('hide');render()}else{$('#app').classList.add('hide')}}
$('#signin').onclick=()=>{let m=mm($('#who').value);if($('#pass').value===m.password){cur=m.id;localStorage.setItem(K+'cur',cur);boot()}else alert('Incorrect password')};
function render(){profileIcon();renderProfiles();renderPosts();renderMemories();renderMedia();renderFiles();renderGoals();renderEvents();renderNotes();$('#nc').textContent=d.notes.filter(x=>x.unread).length;setupDynamic()}
function renderProfiles(){$('#profilesGrid').innerHTML=members.map(x=>`<article class="profile"><div class="avatar">${x.photo?`<img src="${x.photo}" alt="${esc(x.name)}">`:esc(x.name[0])}</div><h4>${esc(x.name)}</h4><p>${esc(x.bio)}</p><small>Personal blog • Private member</small></article>`).join('')}
function renderPosts(){$('#postsList').innerHTML=d.posts.map(p=>`<article class="post"><div class="meta"><b>${esc(mm(p.member).name)}</b> • ${esc(p.date||'Just now')}</div><p>${esc(p.text)}</p><div class="actions"><button data-like="${p.id}">♥ ${p.likes||0}</button><button data-comment="${p.id}">💬 Comment</button><button data-share="${p.id}">↗ Share</button>${p.member===cur?`<button class="dangerText" data-delete-post="${p.id}">🗑 Delete</button>`:''}</div>${(p.comments||[]).map(c=>`<div class="comment"><small><b>${esc(mm(c.member).name)}</b>: ${esc(c.text)}</small></div>`).join('')}</article>`).join('')||'<div class="empty">No posts yet. Share the first thought.</div>'}
$('#post').onclick=()=>{let t=$('#postText').value.trim();if(!t)return;d.posts.unshift({id:Date.now(),member:cur,text:t,date:new Date().toLocaleString(),likes:0,comments:[]});save('posts',d.posts);note(me().name+' shared a new post.');$('#postText').value='';render()};
$('#postsList').onclick=e=>{let l=e.target.closest('[data-like]'),c=e.target.closest('[data-comment]'),s=e.target.closest('[data-share]'),del=e.target.closest('[data-delete-post]');if(l){let p=d.posts.find(x=>x.id==l.dataset.like);p.likes=(p.likes||0)+1;save('posts',d.posts);render()}if(c){let p=d.posts.find(x=>x.id==c.dataset.comment),t=prompt('Write a comment');if(t){p.comments=p.comments||[];p.comments.push({member:cur,text:t});save('posts',d.posts);render()}}if(del&&confirm('Delete this shared post?')){d.posts=d.posts.filter(x=>x.id!=del.dataset.deletePost);save('posts',d.posts);render()}if(s)sharePost(+s.dataset.share)};
function sharePost(id){let p=d.posts.find(x=>x.id==id);if(!p)return;$('#shareText').textContent=p.text;$('#shareD').dataset.text=p.text;$('#shareD').showModal()}
$('#shareD').onclick=e=>{let b=e.target.closest('[data-share]');if(!b)return;let text=$('#shareD').dataset.text||'',u=location.href,enc=encodeURIComponent(text+'\n'+u),type=b.dataset.share;if(type==='whatsapp')window.open('https://wa.me/?text='+enc,'_blank');if(type==='mail')location.href='mailto:?subject='+encodeURIComponent('Three Minds Hub post')+'&body='+enc;if(type==='gmail')window.open('https://mail.google.com/mail/?view=cm&fs=1&su='+encodeURIComponent('Three Minds Hub post')+'&body='+enc,'_blank');if(type==='facebook')window.open('https://www.facebook.com/sharer/sharer.php?u='+encodeURIComponent(u),'_blank');if(type==='copy')navigator.clipboard?.writeText(text+' '+u);if(type==='x')window.open('https://twitter.com/intent/tweet?text='+enc,'_blank');};
function openMem(id){let x=id&&d.memories.find(y=>y.id==id);if(!x&&d.memories.length>=10)return alert('Maximum 10 memories reached. Delete one before adding another.');$('#mid').value=x?.id||'';$('#mn').value=x?.title||'';$('#md').value=x?.date||new Date().toISOString().slice(0,10);$('#mx').value=x?.text||'';$('#mp').value='';$('#mt').textContent=x?'Update memory':'Add memory';$('#memD').showModal()};$('#addMem').onclick=()=>openMem();
$('#memF').onsubmit=async e=>{e.preventDefault();let id=$('#mid').value,f=$('#mp').files[0],photo=f?await readFile(f):'';if(id){let x=d.memories.find(y=>y.id==id);Object.assign(x,{title:$('#mn').value,date:$('#md').value,text:$('#mx').value});if(photo)x.photo=photo;note('Memory updated.')}else{d.memories.unshift({id:Date.now(),title:$('#mn').value,date:$('#md').value,text:$('#mx').value,photo,member:cur});d.memories=d.memories.slice(0,10);note('New memory added.')}save('memories',d.memories);$('#memD').close();render()};
function renderMemories(){$('#memoriesGrid').innerHTML=d.memories.map(x=>`<article class="memory" style="${x.photo?`background-image:url('${x.photo}')`:''}"><div class="ctrl"><button data-edm="${x.id}">Edit</button><button data-delm="${x.id}">Delete</button></div><small>${fmt(x.date)} • ${esc(mm(x.member).name)}</small><h4>${esc(x.title)}</h4><p>${esc(x.text)}</p></article>`).join('')||'<div class="empty">No memories yet.</div>';let h=$('#memories h3');if(h)h.innerHTML='Memories <small class="max10">10 maximum</small>'}
$('#memoriesGrid').onclick=e=>{let x=e.target.closest('[data-delm]'),y=e.target.closest('[data-edm]');if(x&&confirm('Delete memory?')){d.memories=d.memories.filter(z=>z.id!=x.dataset.delm);save('memories',d.memories);render()}if(y)openMem(+y.dataset.edm)};
$('#mediaInput').onchange=async e=>{for(const f of e.target.files)d.media.unshift({id:Date.now()+Math.random(),name:f.name,type:f.type.startsWith('video')?'video':f.type.startsWith('audio')?'audio':'image',data:await readFile(f),member:cur,date:new Date().toISOString().slice(0,10)});save('media',d.media);note('New album media uploaded.');e.target.value='';render()};
function renderMedia(){let q=($('#mediaSearch')?.value||'').toLowerCase();$('#mediaGrid').innerHTML=d.media.filter(x=>x.name.toLowerCase().includes(q)).map(x=>`<article class="media"><div>${x.type==='image'?`<img src="${x.data}" alt="${esc(x.name)}">`:x.type==='video'?`<video src="${x.data}" controls></video>`:`<audio src="${x.data}" controls></audio>`}</div><p>${esc(x.name)}<br><small>Uploaded by ${esc(mm(x.member).name)}</small></p></article>`).join('')||'<div class="empty">Add an image, video or audio file to create your private album.</div>'};$('#mediaSearch').oninput=renderMedia;
$('#fileInput').onchange=async e=>{for(const f of e.target.files){let cat=prompt('Category: Manual Testing / Selenium / Playwright / API & Postman / SQL & Database / Accessibility / CI/CD / Other','Other')||'Other';d.files.unshift({id:Date.now()+Math.random(),name:f.name,size:f.size,data:await readFile(f),cat,member:cur,date:new Date().toISOString().slice(0,10),type:f.type})}save('files',d.files);note(e.target.files.length+' learning file(s) uploaded by '+me().name);e.target.value='';render()};
function renderFiles(){let q=($('#fileSearch')?.value||'').toLowerCase(),cat=$('#folder')?.value||'All categories';let a=d.files.filter(x=>(cat==='All categories'||x.cat===cat)&&x.name.toLowerCase().includes(q));$('#files').innerHTML=a.map(x=>`<div class="file"><div class="fileIcon">${esc((x.name.split('.').pop()||'FILE').toUpperCase().slice(0,5))}</div><div><strong>${esc(x.name)}</strong><br><small>${esc(x.cat)} • Uploaded by ${esc(mm(x.member).name)} • ${fmt(x.date)}</small></div><div class="fileActions"><button data-view-file="${x.id}">👁 View</button><button data-dlf="${x.id}">🗑 Delete</button></div></div>`).join('')||'<div class="empty">No learning documents found.</div>'};$('#fileSearch').oninput=renderFiles;$('#folder').onchange=renderFiles;
$('#files').onclick=e=>{let v=e.target.closest('[data-view-file]'),b=e.target.closest('[data-dlf]');if(v){let x=d.files.find(z=>z.id==v.dataset.viewFile);if(x?.data)window.open(x.data,'_blank')}if(b){d.files=d.files.filter(x=>x.id!=b.dataset.dlf);save('files',d.files);render()}};
$('#goalAdd').onclick=()=>$('#goalD').showModal();$('#goalF').onsubmit=e=>{e.preventDefault();d.goals.push({id:Date.now(),t:$('#gt').value,p:Math.max(0,Math.min(100,+$('#gp').value||0)),member:cur});save('goals',d.goals);note('Learning goal created.');$('#goalD').close();render()};
function renderGoals(){$('#goalsList').innerHTML=d.goals.map(x=>`<div class="goal"><button class="rowDelete" title="Delete goal" data-dgoal="${x.id}">🗑</button><b>${esc(x.t)}</b><small>${x.p}%</small><div class="progress"><i style="width:${x.p}%"></i></div></div>`).join('')||'<p>No learning goals yet.</p>'}
$('#goalsList').onclick=e=>{let b=e.target.closest('[data-dgoal]');if(b&&confirm('Delete this learning goal?')){d.goals=d.goals.filter(x=>x.id!=b.dataset.dgoal);save('goals',d.goals);render()}};
$('#eventAdd').onclick=()=>$('#eventD').showModal();$('#eventF').onsubmit=e=>{e.preventDefault();d.events.push({id:Date.now(),t:$('#et').value,date:$('#ed').value,time:$('#ei').value,email:$('#ee').value,n:$('#ex').value,member:cur});save('events',d.events);note('Event added to your calendar.');$('#eventD').close();render()};
function renderEvents(){$('#eventsList').innerHTML=d.events.map(x=>`<div class="event"><button class="rowDelete" title="Delete event" data-devent="${x.id}">🗑</button><b>${esc(x.t)}</b><br><small>${fmt(x.date)} ${esc(x.time||'')} ${x.email?`• ${esc(x.email)}`:''}</small>${x.n?`<p>${esc(x.n)}</p>`:''}<div class="actions"><button data-gmail-event="${x.id}">✉ Gmail</button><button data-mail-event="${x.id}">📧 Email</button></div></div>`).join('')||'<p>No events yet.</p>'}
$('#eventsList').onclick=e=>{let del=e.target.closest('[data-devent]'),g=e.target.closest('[data-gmail-event]'),m=e.target.closest('[data-mail-event]');if(del&&confirm('Delete this event?')){d.events=d.events.filter(x=>x.id!=del.dataset.devent);save('events',d.events);render()}let x=g?d.events.find(z=>z.id==g.dataset.gmailEvent):m?d.events.find(z=>z.id==m.dataset.mailEvent):null;if(x){let body=`Event: ${x.t}\nDate: ${fmt(x.date)}\nTime: ${x.time||''}\nNotes: ${x.n||''}`;let sub=encodeURIComponent('Three Minds Hub - '+x.t);let to=encodeURIComponent(x.email||'');let b=encodeURIComponent(body);if(g)window.open('https://mail.google.com/mail/?view=cm&fs=1&to='+to+'&su='+sub+'&body='+b,'_blank');else location.href='mailto:'+to+'?subject='+sub+'&body='+b}};
function renderNotes(){$('#notes').innerHTML=d.notes.map(x=>`<div class="notification ${x.unread?'unread':'readNote'}"><span>${x.unread?'🔔':'✓'} ${esc(x.text)}</span><small>${x.unread?'Unread':'Read'}</small></div>`).join('')||'<div class="empty">No notifications.</div>'}
function setupNotifications(){let h=$('#notifications .head');if(h&&!$('#clearNotes')){let b=document.createElement('button');b.id='clearNotes';b.className='alt clearBtn';b.innerHTML='🧹 Clear all';b.onclick=()=>{if(confirm('Clear all notifications?')){d.notes=[];save('notes',d.notes);render()}};h.appendChild(b)}$('#read').onclick=()=>{d.notes.forEach(x=>x.unread=0);save('notes',d.notes);render()}}
function profile(){let x=me();$('#pn').value=x.name;$('#pb').value=x.bio;$('#pp').value='';$('#photo').value='';$('#profileD').showModal()};$('#edit').onclick=profile;$('#edit2').onclick=profile;$('#me').onclick=profile;
$('#profileF').onsubmit=async e=>{e.preventDefault();let x=me(),f=$('#photo').files[0];x.name=$('#pn').value;x.bio=$('#pb').value;if($('#pp').value)x.password=$('#pp').value;if(f)x.photo=await readFile(f);save('members',members);$('#profileD').close();render()};
function setupDynamic(){setupNotifications();$$('[data-close]').forEach(x=>x.onclick=()=>x.closest('dialog').close());let sh=$('#shareD .shareOptions');if(sh&&!sh.querySelector('[data-share="gmail"]')){let b=document.createElement('button');b.type='button';b.dataset.share='gmail';b.textContent='Gmail';sh.appendChild(b)}let h=$('.headerTools');if(h&&!h.querySelector('.flagIndia')){let f=document.createElement('span');f.className='flagIndia';f.title='India';h.prepend(f)}profileIcon()}
if(localStorage.getItem(K+'dark')==='true')document.body.classList.add('dark');boot();