const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)],K='tmh3_';
const DEFAULT_MEMBERS=[{id:'m1',name:'Subramaniam',password:'mind1',bio:'Add your story, interests, skills and what you are learning.',photo:''},{id:'m2',name:'Pradap',password:'mind2',bio:'Write your personal blog for your two friends.',photo:''},{id:'m3',name:'Kalaivani',password:'mind3',bio:'A little introduction about me goes here.',photo:''}];
const D={posts:[],memories:[],media:[],files:[],goals:[],events:[],notes:[]};
function load(k,v){try{return JSON.parse(localStorage.getItem(K+k))??structuredClone(v)}catch{return structuredClone(v)}}function save(k,v){localStorage.setItem(K+k,JSON.stringify(v))}
let members=load('members',DEFAULT_MEMBERS);if(members.some(x=>/^Friend (One|Two|Three)$/.test(x.name))){members=DEFAULT_MEMBERS.map((n,i)=>({...n,...(members[i]||{}),name:n.name,password:members[i]?.password||n.password}));save('members',members)}
let d=Object.fromEntries(Object.keys(D).map(k=>[k,load(k,D[k])]));let cur=localStorage.getItem(K+'cur')||'';
function me(){return members.find(x=>x.id===cur)||members[0]}function mm(id){return members.find(x=>x.id===id)||members[0]}function esc(x){return String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]))}function read(f){return new Promise(r=>{const x=new FileReader();x.onload=()=>r(x.result);x.readAsDataURL(f)})}function fmt(x){return x?new Date(x+'T00:00:00').toLocaleDateString(undefined,{day:'numeric',month:'short',year:'numeric'}):''}
function notify(t){d.notes.unshift({id:Date.now()+Math.random(),text:t,unread:1,date:new Date().toLocaleString()});d.notes=d.notes.slice(0,30);save('notes',d.notes)}
function boot(){if($('#who'))$('#who').innerHTML=members.map(x=>`<option value="${x.id}">${esc(x.name)}</option>`).join('');if(cur){$('#login').classList.add('hide');$('#app').classList.remove('hide');render()}else{$('#login').classList.remove('hide');$('#app').classList.add('hide')}}
$('#signin').onclick=()=>{const m=mm($('#who').value);if($('#pass').value===m.password){cur=m.id;localStorage.setItem(K+'cur',cur);$('#pass').value='';boot()}else alert('Incorrect password')};$('#logout').onclick=()=>{localStorage.removeItem(K+'cur');cur='';boot();window.scrollTo(0,0)};
function render(){const m=me();$('#profilesGrid').innerHTML=members.map(x=>`<article class="profile"><div class="avatar">${x.photo?`<img src="${x.photo}" alt="${esc(x.name)}">`:esc(x.name[0])}</div><h4>${esc(x.name)}</h4><p>${esc(x.bio)}</p><small>Personal blog • Member</small></article>`).join('');$('#postsList').innerHTML=d.posts.map(p=>`<article class="post"><div class="meta"><b>${esc(mm(p.member).name)}</b> • ${esc(p.date)}</div><p>${esc(p.text)}</p><div class="actions"><button data-like="${p.id}">♥ ${p.likes||0}</button><button data-com="${p.id}">💬 Comment</button><button data-share="${p.id}">↗ Share</button>${p.member===cur?`<button data-delp="${p.id}" class="dangerText">Delete</button>`:''}</div>${(p.comments||[]).map(c=>`<div class="comment"><small><b>${esc(mm(c.member).name)}</b>: ${esc(c.text)}</small></div>`).join('')}</article>`).join('')||'<div class="empty">No posts yet. Share the first update.</div>';
$('#memoriesGrid').innerHTML=d.memories.map(x=>`<article class="memory" style="${x.photo?`background-image:url('${x.photo}')`:''}"><div class="ctrl"><button data-edm="${x.id}">Edit</button><button data-delm="${x.id}">Delete</button></div><small>${fmt(x.date)} • ${esc(mm(x.member).name)}</small><h4>${esc(x.title)}</h4><p>${esc(x.text)}</p></article>`).join('')||'<div class="empty">No memories yet.</div>';renderMedia();renderFiles();renderGoals();renderEvents();renderNotes();$('#nc').textContent=d.notes.filter(x=>x.unread).length;$('#me').textContent=(m.name||'S').charAt(0).toUpperCase();}
$('#post').onclick=()=>{const t=$('#postText').value.trim();if(t){d.posts.unshift({id:Date.now(),member:cur,text:t,date:new Date().toLocaleString(),likes:0,comments:[]});save('posts',d.posts);notify(me().name+' shared a new post.');$('#postText').value='';render();location.hash='posts'}};
$('#postsList').onclick=e=>{const l=e.target.closest('[data-like]'),c=e.target.closest('[data-com]'),s=e.target.closest('[data-share]'),del=e.target.closest('[data-delp]');if(l){const p=d.posts.find(x=>x.id==l.dataset.like);if(p){p.likes=(p.likes||0)+1;save('posts',d.posts);render()}}if(c){const p=d.posts.find(x=>x.id==c.dataset.com),t=prompt('Comment');if(p&&t){p.comments=p.comments||[];p.comments.push({member:cur,text:t});save('posts',d.posts);notify(me().name+' commented on a post.');render()}}if(s){const p=d.posts.find(x=>x.id==s.dataset.share);if(p){$('#shareText').textContent=p.text;$('#shareD').dataset.post=p.id;$('#shareD').showModal()}}if(del&&confirm('Delete your shared post?')){d.posts=d.posts.filter(x=>x.id!=del.dataset.delp);save('posts',d.posts);render()}};
$('#shareD').onclick=e=>{const b=e.target.closest('[data-share]');if(!b)return;const p=d.posts.find(x=>x.id==$('#shareD').dataset.post);if(!p)return;const text=`${me().name} shared on Three Minds Hub: ${p.text}`,url=location.href;if(b.dataset.share==='whatsapp')window.open('https://wa.me/?text='+encodeURIComponent(text+' '+url),'_blank');if(b.dataset.share==='mail')location.href='mailto:?subject='+encodeURIComponent('Three Minds Hub post')+'&body='+encodeURIComponent(text+'\n'+url);if(b.dataset.share==='facebook')window.open('https://www.facebook.com/sharer/sharer.php?u='+encodeURIComponent(url),'_blank');if(b.dataset.share==='copy')navigator.clipboard?.writeText(text+' '+url).then(()=>alert('Post link copied.'));$('#shareD').close()};
function openMem(id){const x=id&&d.memories.find(y=>y.id==id);if(!x&&d.memories.length>=10)return alert('Maximum 10 memories reached. Delete one first.');$('#mid').value=x?.id||'';$('#mn').value=x?.title||'';$('#md').value=x?.date||new Date().toISOString().slice(0,10);$('#mx').value=x?.text||'';$('#mp').value='';$('#mt').textContent=x?'Update memory':'Add memory';$('#memD').showModal()}$('#addMem').onclick=()=>openMem();
$('#memF').onsubmit=async e=>{e.preventDefault();const id=$('#mid').value,f=$('#mp').files[0],photo=f?await read(f):'';if(id){const x=d.memories.find(y=>y.id==id);Object.assign(x,{title:$('#mn').value,date:$('#md').value,text:$('#mx').value});if(photo)x.photo=photo;notify('A memory was updated.')}else{d.memories.unshift({id:Date.now(),title:$('#mn').value,date:$('#md').value,text:$('#mx').value,photo,member:cur});d.memories=d.memories.slice(0,10);notify('New memory added.')}save('memories',d.memories);$('#memD').close();render()};
$('#memoriesGrid').onclick=e=>{const x=e.target.closest('[data-delm]'),y=e.target.closest('[data-edm]');if(x&&confirm('Delete memory?')){d.memories=d.memories.filter(z=>z.id!=x.dataset.delm);save('memories',d.memories);render()}if(y)openMem(+y.dataset.edm)};
$('#fileInput').onchange=async e=>{for(const f of e.target.files){const cat=prompt('Category: Manual Testing / Selenium / Playwright / API & Postman / SQL & Database / Accessibility / CI/CD / Other','Other')||'Other';d.files.unshift({id:Date.now()+Math.random(),name:f.name,size:f.size,type:f.type||'application/octet-stream',data:await read(f),cat,member:cur,date:new Date().toISOString().slice(0,10)})}save('files',d.files);notify(e.target.files.length+' learning file(s) uploaded by '+me().name);e.target.value='';render()};
function renderFiles(){const q=$('#fileSearch').value.toLowerCase(),cat=$('#folder').value,a=d.files.filter(x=>(cat==='All categories'||x.cat===cat)&&x.name.toLowerCase().includes(q));$('#files').innerHTML=a.map(x=>`<div class="file"><div class="fileIcon">${fileIcon(x.type)}</div><strong>${esc(x.name)}</strong><small>${esc(x.cat)} • Uploaded by ${esc(mm(x.member).name)} • ${fmt(x.date)}</small><div class="fileActions"><button data-viewf="${x.id}">View</button><button data-dlf="${x.id}">Delete</button></div></div>`).join('')||'<div class="empty">No files found.</div>'}
function fileIcon(t){if(t.includes('pdf'))return'PDF';if(t.includes('word')||t.includes('document'))return'DOC';if(t.includes('sheet')||t.includes('excel'))return'XLS';if(t.includes('presentation')||t.includes('powerpoint'))return'PPT';if(t.startsWith('image'))return'IMG';if(t.startsWith('video'))return'VID';if(t.startsWith('audio'))return'AUD';return'FILE'}$('#fileSearch').oninput=renderFiles;$('#folder').onchange=renderFiles;$('#files').onclick=e=>{const b=e.target.closest('[data-dlf]'),v=e.target.closest('[data-viewf]');if(b){d.files=d.files.filter(x=>x.id!=b.dataset.dlf);save('files',d.files);render()}if(v){const f=d.files.find(x=>x.id==v.dataset.viewf);if(f){const w=window.open();if(w){w.document.write(`<title>${esc(f.name)}</title><body style="margin:0;background:#111;display:grid;place-items:center;min-height:100vh">${f.type.startsWith('image')?`<img src="${f.data}" style="max-width:100%;max-height:100vh">`:f.type.startsWith('video')?`<video src="${f.data}" controls autoplay style="max-width:100%;max-height:100vh"></video>`:f.type.startsWith('audio')?`<audio src="${f.data}" controls autoplay></audio>`:`<iframe src="${f.data}" style="width:100%;height:100vh;border:0;background:#fff"></iframe>`}</body>`);w.document.close()}}}};
$('#mediaInput').onchange=async e=>{for(const f of e.target.files)d.media.unshift({id:Date.now()+Math.random(),name:f.name,type:f.type.startsWith('video')?'video':f.type.startsWith('audio')?'audio':'image',mime:f.type,data:await read(f),member:cur,date:new Date().toISOString().slice(0,10)});save('media',d.media);notify('Media uploaded by '+me().name);e.target.value='';render()};function renderMedia(){const q=$('#mediaSearch').value.toLowerCase();$('#mediaGrid').innerHTML=d.media.filter(x=>x.name.toLowerCase().includes(q)).map(x=>`<article class="media"><div>${x.type==='image'?`<img src="${x.data}" alt="${esc(x.name)}">`:x.type==='video'?`<video src="${x.data}" controls preload="metadata"></video>`:`<div class="audioBox"><span>♫</span><audio src="${x.data}" controls></audio></div>`}</div><p>${esc(x.name)}<br><small>Uploaded by ${esc(mm(x.member).name)}</small></p></article>`).join('')||'<div class="empty">No media yet. Add a photo, video or audio file.</div>'}$('#mediaSearch').oninput=renderMedia;
$('#goalAdd').onclick=()=>$('#goalD').showModal();$('#goalF').onsubmit=e=>{e.preventDefault();d.goals.push({id:Date.now(),t:$('#gt').value,p:+$('#gp').value||0});save('goals',d.goals);notify('Learning goal created');$('#goalD').close();render()};function renderGoals(){$('#goalsList').innerHTML=d.goals.map(x=>`<div class="goal"><b>${esc(x.t)}</b><small>${x.p}%</small><div class="progress"><i style="width:${x.p}%"></i></div></div>`).join('')||'<p>No goals yet.</p>'}
$('#eventAdd').onclick=()=>$('#eventD').showModal();$('#eventF').onsubmit=e=>{e.preventDefault();const email=$('#ee').value.trim(),event={id:Date.now(),t:$('#et').value,date:$('#ed').value,time:$('#ei').value,email,n:$('#ex').value};d.events.unshift(event);save('events',d.events);notify('Event added'+(email?' • email reminder prepared':''));$('#eventD').close();render();if(email){const subject=encodeURIComponent('Three Minds Hub event: '+event.t),body=encodeURIComponent(`Event: ${event.t}\nDate: ${fmt(event.date)}\nTime: ${event.time||'Not specified'}\n\n${event.n||''}`);setTimeout(()=>{if(confirm('Open your mail app to send this event notification to '+email+'?'))location.href=`mailto:${email}?subject=${subject}&body=${body}`},100)}};function renderEvents(){$('#eventsList').innerHTML=d.events.map(x=>`<div class="event"><b>${esc(x.t)}</b><br><small>${fmt(x.date)} ${esc(x.time||'')} ${x.email?`• ${esc(x.email)}`:''}<br>${esc(x.n||'')}</small>${x.email?`<button class="miniBtn" data-mail="${x.id}">✉ Send reminder</button>`:''}</div>`).join('')||'<p>No events yet.</p>'}$('#eventsList').onclick=e=>{const b=e.target.closest('[data-mail]');if(b){const x=d.events.find(v=>v.id==b.dataset.mail);if(x)location.href=`mailto:${x.email}?subject=${encodeURIComponent('Reminder: '+x.t)}&body=${encodeURIComponent('Event: '+x.t+'\nDate: '+fmt(x.date)+'\nTime: '+(x.time||'Not specified')+'\n'+(x.n||''))}`}};
function renderNotes(){$('#notes').innerHTML=d.notes.map(x=>`<div class="notification ${x.unread?'unread':'readNote'}"><div><b>🔔</b> ${esc(x.text)}</div><small>${esc(x.date||'')}</small></div>`).join('')||'<div class="empty">No notifications.</div>'}$('#read').onclick=()=>{d.notes.forEach(x=>x.unread=0);save('notes',d.notes);renderNotes();$('#nc').textContent='0';};
async function profile(){const x=me();$('#pn').value=x.name;$('#pb').value=x.bio;$('#pp').value='';$('#photo').value='';$('#profileD').showModal()}$('#edit').onclick=profile;$('#edit2').onclick=profile;$('#me').onclick=profile;$('#profileF').onsubmit=async e=>{e.preventDefault();const x=me(),f=$('#photo').files[0];x.name=$('#pn').value;x.bio=$('#pb').value;if($('#pp').value)x.password=$('#pp').value;if(f)x.photo=await read(f);save('members',members);$('#profileD').close();boot()};
function applyTheme(dark){document.body.classList.toggle('dark',dark);localStorage.setItem(K+'dark',dark?'true':'false');$('#themeToggle')?.classList.toggle('on',dark)}applyTheme(localStorage.getItem(K+'dark')==='true');$('#themeToggle').onclick=()=>applyTheme(!document.body.classList.contains('dark'));
$('#hamb').onclick=()=>$('#menu').classList.add('open');$('#x').onclick=()=>$('#menu').classList.remove('open');$$('#menu a').forEach(a=>a.onclick=()=>$('#menu').classList.remove('open'));$$('[data-close]').forEach(x=>x.onclick=()=>x.closest('dialog').close());boot();