(() => {
  const $ = s => document.querySelector(s);
  const $$ = s => [...document.querySelectorAll(s)];
  const rememberKey = 'tmh3_remember';
  function css(){const s=document.createElement('style');s.textContent=`#rememberRow{display:flex!important;align-items:center!important;gap:9px!important;margin:2px 0 8px!important;color:var(--muted);font-size:12px;cursor:pointer}#rememberRow input{width:17px!important;height:17px!important;accent-color:#e85d3f;margin:0}.premiumLogin{background:linear-gradient(145deg,var(--card),#f2eadf)!important;border:1px solid #e3d5c3!important}body.dark .premiumLogin{background:linear-gradient(145deg,var(--card),#141612)!important}.premiumCampfire{width:min(560px,92vw);aspect-ratio:510/185;border-radius:28px;position:relative;overflow:hidden;background:#17202d center/cover no-repeat url('./assets/three-minds-campfire.webp');box-shadow:0 30px 80px #0003;border:1px solid #ffffff30}.premiumCampfire:after{content:'';position:absolute;inset:0;background:linear-gradient(180deg,transparent 55%,#0003 100%);pointer-events:none}.campfireText{position:absolute;z-index:8;left:28px;right:28px;bottom:22px;color:#fff;display:flex;flex-direction:column;text-shadow:0 2px 8px #000}.campfireText strong{font-size:13px;letter-spacing:2px;text-transform:uppercase;color:#ffc86a}.campfireText span{font-size:18px;font-weight:750;max-width:430px}.social{gap:18px!important}.social a{width:auto!important;height:auto!important;color:var(--ink)!important;font-size:25px!important;transition:.2s}.social a:hover{transform:translateY(-3px);color:var(--a)!important}.flagIndia{width:28px!important;height:19px!important;background:transparent!important;border:0!important;box-shadow:none!important}.flagIndia svg{width:100%;height:100%;display:block}.headerTools{gap:12px!important}.deleteLabel{font-size:11px}.max10{font-size:13px!important;font-weight:750!important}@media(max-width:600px){.premiumCampfire{width:100%;border-radius:22px}.campfireText span{font-size:15px}.social{gap:14px!important}}`;document.head.appendChild(s);}
  function flag(){const f=$('.flagIndia');if(!f)return;f.innerHTML='<svg viewBox="0 0 24 16" aria-label="India flag" role="img"><rect width="24" height="16" rx="1" fill="#fff"/><rect width="24" height="5.33" fill="#ff9933"/><rect y="10.67" width="24" height="5.33" fill="#138808"/><circle cx="12" cy="8" r="2.1" fill="none" stroke="#000080" stroke-width=".55"/><path d="M12 5.7v4.6M9.7 8h4.6M10.4 6.4l3.2 3.2M13.6 6.4l-3.2 3.2" stroke="#000080" stroke-width=".28"/></svg>';}
  function social(){const s=$('.social');if(!s)return;s.innerHTML='<a aria-label="Facebook" title="Facebook" href="https://www.facebook.com/" target="_blank" rel="noopener"><i class="fa-brands fa-facebook-f"></i></a><a aria-label="Instagram" title="Instagram" href="https://www.instagram.com/" target="_blank" rel="noopener"><i class="fa-brands fa-instagram"></i></a><a aria-label="X / Twitter" title="X / Twitter" href="https://x.com/" target="_blank" rel="noopener"><i class="fa-brands fa-x-twitter"></i></a><a aria-label="WhatsApp" title="WhatsApp" href="https://web.whatsapp.com/" target="_blank" rel="noopener"><i class="fa-brands fa-whatsapp"></i></a><a aria-label="YouTube" title="YouTube" href="https://www.youtube.com/" target="_blank" rel="noopener"><i class="fa-brands fa-youtube"></i></a><a aria-label="LinkedIn" title="LinkedIn" href="https://www.linkedin.com/" target="_blank" rel="noopener"><i class="fa-brands fa-linkedin-in"></i></a>';}
  function campfire(){const h=$('.heroLogo');if(!h)return;h.innerHTML='<div class="premiumCampfire" role="img" aria-label="Three Minds campfire scene with Subramaniam, Pradap and Kalaivani together"><div class="campfireText"><strong>OUR DIGITAL CAMPFIRE</strong><span>Three friends. One bond. A lifetime of memories, ideas and growth.</span></div></div>';const p=$('.hero>div:first-child>p:not(.eyebrow)');if(p)p.textContent='A private, beautifully crafted space where three friends keep memories, share moments and grow their skills together.';}
  function remember(){const pass=$('#pass');if(!pass||$('#rememberMe'))return;const row=document.createElement('label');row.id='rememberRow';row.innerHTML='<input id="rememberMe" type="checkbox"><span>Remember me on this device</span>';pass.insertAdjacentElement('afterend',row);if(localStorage.getItem(rememberKey)==='1'){$('#rememberMe').checked=true;const last=localStorage.getItem('tmh3_last_member');if(last&&$('#who').querySelector(`option[value="${last}"]`))$('#who').value=last;}const sign=$('#signin');if(sign&&!sign.dataset.rememberBound){sign.dataset.rememberBound='1';sign.addEventListener('click',()=>{setTimeout(()=>{const id=$('#who')?.value;if($('#rememberMe')?.checked&&id){localStorage.setItem(rememberKey,'1');localStorage.setItem('tmh3_last_member',id)}else{localStorage.removeItem(rememberKey);localStorage.removeItem('tmh3_last_member')}},100);});}}
  function login(){const card=$('.loginCard');if(!card)return;card.classList.add('premiumLogin');const t=card.querySelector('h1');if(t)t.textContent='Welcome back 😊';}
  function closeMenu(){const menu=$('#menu');if(!menu)return;$$('#menu a').forEach(a=>{if(!a.dataset.safeClose){a.dataset.safeClose='1';a.addEventListener('click',()=>menu.classList.remove('open'));}});}
  function firstProfile(){const grid=$('#profilesGrid');const id=localStorage.getItem('tmh3_cur');if(!grid||!id||!window.members)return;const m=window.members.find(x=>x.id===id);if(!m)return;const card=[...grid.children].find(c=>c.querySelector('h4')?.textContent===m.name);if(card&&grid.firstElementChild!==card)grid.prepend(card);}
  function init(){css();login();remember();social();flag();campfire();closeMenu();firstProfile();}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();
})();